apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: john-developer # example
spec:
  # This is an encoded CSR. Change this to the base64-encoded contents of myuser.csr
  signerName: kubernetes.io/kube-apiserver-client
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0VhbTlvYmpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQUtVTi9hWTVHM1Vqd1FzanhtOTJJY2IxR09yMlZ0TEpySlJGbDBmcTNkMWkxaUQvClpYTmV3bVFPbENVdTc5L3lwR3RJei9ndXdGRHc4RjlXaDNpcnZ3YkdMRkJOYXYwOVlnVFRzdUprOGJhZVBGMWgKRStEZzIzOHJwT1lZbEd0OW5rVEJZaFVhNDd2Y0pKWUZrc1dvRXlVTmRQQUZsVURvMFQ1QlNPQTd4YzY5ajR5UApzQVI3bFpVdGp5S01sbVVvM1BoUW9vZWVUTVlNUkh3T3BHbTlVd3dORTRMK215SGRkbDNTcWY1aEJhNE5xemc5CkllbWdldUVJaDc0MERJNjZhdW1hQXNEOU5GSjY2YVJmNTlNTk5BNTdpNVdPVjYzUFhRS2h4Si9hZWpwVERIVjgKalYzUXhZckNFV1JJMnZieHhXWnBhUVdoVHJ2RzZkMHE4NHZoekwwQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQnJxZnZmcHpDbG5XdUJMSWJvbVUvQUFTODRxKzJ6eWR1Skh5YXRmQTA0UUdQRVFOZ3lFZGxvCmhtYTZ4STZ2NUJDYk9DVFN5N2NnSXdSTEk3MWpJYUJWTmtzVnRtN1dHcTIvUG9ab1UvSDRiVmFyWEV1V3FUVU8Kbm9ReTNZTnF1TVhzSnFLNFNVVkgxR25KREdvMkVWYVV2NjJqdTNicTR6L1hFMld1V1VWUHZyR1VscmtJUEdONApJRkt2c3QweWd1L2pHMm1OdDVjWkVoR2dzd3h2RUdVV1NzY1VIbGxFNmE2dWhXcWR0NmRHUVdKUjFicGZVL1Z0CnR5LzEvaFRZWmh0Vm9oVFhLa3BZdS85TTBTa1haMG02c3dIanRDRm5EUndIeGRSTWxxVmRkUjR5QXh1RUU3MDMKV3RQaFBVOFhWSERMNkxvUERWSytGMEdiMWxrU2MrV3QKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  expirationSeconds: 86400  # one day
  usages:
  - digital signature
  - key encipherment
  - client auth


  ###create request from /root/CKA/john.csr file using command cat /root/CKA/john.csr | base64 | tr -d "\n"
  ####kubectl get csr john-developer -o yaml
